### ISSUE TITLE
Linefly flickers when using tab to select items in cmp list

### ISSUE THREAD

**Issue by qbnil** [bluz71/nvim-linefly#10] opened 2024-05-17 18:42 UTC
![image](https://github.com/bluz71/nvim-linefly/assets/130576530/fbbfa7f5-ddc7-4f3c-9bae-ac367fed8a56)
the moment i select the next item the lualine kinda updates and flickers for millisecond, and that happends everytime

**Comment by bluz71** [comment] 2024-05-18 02:59
Hello @qbnil,

I use `nvim-cmp` with `linefly` and I get no flickering. I understand the effect you are describing, I sometimes experience that in normal Vim.

Since I do not experience your issue, I can only recommend that you edit down your Neovim configuration to the most minimal state to reproduce the issue and then post that configuration here so I can debug the issue.

You may be experience an interaction with another plugin?
Or you may have set an option that triggers this issue, or I may have set an option that avoids this issue. I am not sure.

Sorry, I can't be more helpful at the moment, you need to do some work at your end, but I am pretty confident that if we work together we can sort this out.

Best regards,

Dennis.

**Comment by bluz71** [comment] 2024-05-18 10:36
Also provide: Neovim version, Platform (Linux, Mac?), and Terminal (Alacritty, kitty, iTerm2?).

**Comment by qbnil** [comment] 2024-05-18 14:49
I have Neovim v0.9.5 running Arch Linux with kitty as my terminal, i got rid of linefly to figure out how the ordinary built-in status line behaves and that was also relevent for it. The flickering keeps on happening when pressing tab. Don't really know what's causing that

**Comment by qbnil** [comment] 2024-05-18 14:52
I tried setting the keymap to a different binding that the issue was still there

**Comment by serranomorante** [comment] 2024-05-19 02:12
https://github.com/hrsh7th/nvim-cmp/issues/1396

**Comment by bluz71** [comment] 2024-05-19 07:49
Thanks @serranomorante. In my experience `cmdheight=0` results in lots of flicker, hence I always use default `cmdheight` (of `1`).

However, we can't be sure that @qbnil is using that setting. Experimentation needed to debug the issue at their end.

My setup, Neovim `0.10` + `nvim-cmp` + default `cmdheight=1` on Linux via Alacritty, no flicker at all when navigating the completion window.

Closing this issue since it is an upstream issue (even happens with default Neovim `statusline`). So, there is nothing I can fix here to solve this issue.

Best of luck @qbnil.

**Closed as completed by bluz71** 2024-05-19 07:49 UTC

**Comment by qbnil** [comment] 2024-05-19 09:18
You were correct on the cmdheight thing, but doesn't it seem to you a little bit disgusting the way it looks with cmdheight = 1, the gap between the actual line and the bottom border

**Comment by bluz71** [comment] 2024-05-19 11:02
The gap is the Neovim command line, it has existed in Vim and Vi editors since the 1970s relating their it `ed` line editing heritage. It may not be pretty, but it is highly functional.

`cmdheight=0` has many problems, not just flickering. I would only use it with the [noice](https://github.com/folke/noice.nvim) plugin. I personally find `noice` too extreme (in how it changes Neovim behaviour and looks), but it makes `cmdheight=0` functional.

Best of luck.

**Comment by qbnil** [comment] 2024-05-19 11:06
Gotcha, thx, gotta find out how this gap is useful for me except the messages begin printed down there
